FROM bfabio/publiccode-parser-go:latest

RUN go get -u github.com/reviewdog/reviewdog/cmd/reviewdog && rm -fr /go/pkg

COPY .reviewdog.yml .reviewdog.yml

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
